import type { Doctor } from "@/lib/tipos";

export const SEED_DOCTORES: Doctor[] = [
  // ===== METROPOLITANO (Quito) =====
  {
    id: "dr-cardenas-juan",
    name: "Dr. Juan Cárdenas Aguirre",
    specialty: "Cardiología",
    hospitalId: "metropolitano",
    hospitalName: "Hospital Metropolitano",
    rating: 4.8,
    yearsExperience: 22,
    languages: ["es", "en"],
    schedule: "Lun-Vie 9:00-13:00 y 15:00-18:00",
    bio: "Cardiólogo intervencionista, miembro de la Sociedad Ecuatoriana de Cardiología.",
  },
  {
    id: "dra-mendoza-paula",
    name: "Dra. Paula Mendoza Romero",
    specialty: "Neurología",
    hospitalId: "metropolitano",
    hospitalName: "Hospital Metropolitano",
    rating: 4.7,
    yearsExperience: 18,
    languages: ["es", "en"],
    schedule: "Mar-Sáb 8:00-14:00",
    bio: "Especialista en cefaleas y migraña refractaria, fellow en Hospital Quirón Madrid.",
  },
  {
    id: "dr-vega-ignacio",
    name: "Dr. Ignacio Vega Pesantez",
    specialty: "Traumatología",
    hospitalId: "metropolitano",
    hospitalName: "Hospital Metropolitano",
    rating: 4.6,
    yearsExperience: 15,
    languages: ["es"],
    schedule: "Lun-Vie 7:30-13:00",
    bio: "Traumatólogo, cirugía de rodilla y artroscopia.",
  },

  // ===== VOZ ANDES =====
  {
    id: "dra-paez-carla",
    name: "Dra. Carla Páez Suárez",
    specialty: "Pediatría",
    hospitalId: "voz_andes",
    hospitalName: "Hospital Voz Andes",
    rating: 4.7,
    yearsExperience: 16,
    languages: ["es", "en"],
    schedule: "Lun-Vie 8:00-13:00 y 15:00-19:00",
    bio: "Pediatra con sub-especialidad en gastroenterología infantil.",
  },
  {
    id: "dr-tobar-luis",
    name: "Dr. Luis Tobar Andrade",
    specialty: "Reumatología",
    hospitalId: "voz_andes",
    hospitalName: "Hospital Voz Andes",
    rating: 4.5,
    yearsExperience: 20,
    languages: ["es"],
    schedule: "Mar-Jue 9:00-12:00",
    bio: "Reumatólogo con enfoque en artritis y enfermedades autoinmunes.",
  },
  {
    id: "dr-zambrano-andres",
    name: "Dr. Andrés Zambrano Cordero",
    specialty: "Emergencias",
    hospitalId: "voz_andes",
    hospitalName: "Hospital Voz Andes",
    rating: 4.4,
    yearsExperience: 12,
    languages: ["es", "en"],
    schedule: "24 horas con turnos rotativos",
    bio: "Médico emergenciólogo, certificado en Manchester Triage System.",
  },

  // ===== AXXIS =====
  {
    id: "dra-ortega-sofia",
    name: "Dra. Sofía Ortega León",
    specialty: "Neurología",
    hospitalId: "axxis",
    hospitalName: "Hospital Axxis",
    rating: 4.8,
    yearsExperience: 14,
    languages: ["es", "en"],
    schedule: "Lun-Vie 14:00-19:00",
    bio: "Neuróloga especializada en cefaleas, vértigo y migraña crónica.",
  },
  {
    id: "dr-bastidas-rafael",
    name: "Dr. Rafael Bastidas Vintimilla",
    specialty: "Cardiología",
    hospitalId: "axxis",
    hospitalName: "Hospital Axxis",
    rating: 4.7,
    yearsExperience: 19,
    languages: ["es"],
    schedule: "Lun-Vie 9:00-13:00",
    bio: "Cardiólogo clínico, ecocardiografía y holter.",
  },
  {
    id: "dra-romero-isabella",
    name: "Dra. Isabella Romero Crespo",
    specialty: "Endocrinología",
    hospitalId: "axxis",
    hospitalName: "Hospital Axxis",
    rating: 4.6,
    yearsExperience: 11,
    languages: ["es", "en"],
    schedule: "Mar-Vie 15:00-19:00",
    bio: "Endocrinóloga, manejo de diabetes y patologías tiroideas.",
  },

  // ===== DE LOS VALLES =====
  {
    id: "dra-jimenez-valentina",
    name: "Dra. Valentina Jiménez Loor",
    specialty: "Ginecología",
    hospitalId: "de_los_valles",
    hospitalName: "Hospital de los Valles",
    rating: 4.7,
    yearsExperience: 17,
    languages: ["es", "en"],
    schedule: "Lun-Sáb 9:00-15:00",
    bio: "Ginecóloga obstetra, atención de embarazo de alto riesgo.",
  },
  {
    id: "dr-vasconez-carlos",
    name: "Dr. Carlos Vásconez Espinosa",
    specialty: "Traumatología",
    hospitalId: "de_los_valles",
    hospitalName: "Hospital de los Valles",
    rating: 4.5,
    yearsExperience: 13,
    languages: ["es"],
    schedule: "Lun-Vie 8:00-14:00",
    bio: "Traumatólogo, esguinces y patología deportiva.",
  },

  // ===== CARLOS ANDRADE =====
  {
    id: "dr-suarez-marco",
    name: "Dr. Marco Suárez Bermeo",
    specialty: "Cardiología",
    hospitalId: "carlos_andrade",
    hospitalName: "Hospital Carlos Andrade Marín",
    rating: 4.2,
    yearsExperience: 25,
    languages: ["es"],
    schedule: "Lun-Vie 8:00-13:00",
    bio: "Cardiólogo del IESS con amplia experiencia en hipertensión.",
  },
  {
    id: "dra-cabrera-monica",
    name: "Dra. Mónica Cabrera Donoso",
    specialty: "Reumatología",
    hospitalId: "carlos_andrade",
    hospitalName: "Hospital Carlos Andrade Marín",
    rating: 4.0,
    yearsExperience: 22,
    languages: ["es"],
    schedule: "Mar-Jue 8:00-12:00",
    bio: "Reumatóloga del IESS, atención de adulto mayor.",
  },

  // ===== ALCÍVAR (Guayaquil) =====
  {
    id: "dra-sanchez-maria",
    name: "Dra. María Sánchez Verduga",
    specialty: "Cardiología",
    hospitalId: "alcivar",
    hospitalName: "Hospital Alcívar",
    rating: 4.7,
    yearsExperience: 20,
    languages: ["es", "en"],
    schedule: "Lun-Vie 9:00-13:00 y 15:00-18:00",
    bio: "Cardióloga clínica, manejo integral de hipertensión.",
  },
  {
    id: "dr-vera-pablo",
    name: "Dr. Pablo Vera Andrade",
    specialty: "Medicina General",
    hospitalId: "alcivar",
    hospitalName: "Hospital Alcívar",
    rating: 4.5,
    yearsExperience: 12,
    languages: ["es"],
    schedule: "Lun-Sáb 7:00-19:00",
    bio: "Médico de atención primaria, consultas generales.",
  },
  {
    id: "dr-icaza-alejandro",
    name: "Dr. Alejandro Icaza Plaza",
    specialty: "Neurología",
    hospitalId: "alcivar",
    hospitalName: "Hospital Alcívar",
    rating: 4.6,
    yearsExperience: 16,
    languages: ["es", "en"],
    schedule: "Mar-Vie 14:00-19:00",
    bio: "Neurólogo, especialista en cefaleas y trastornos del sueño.",
  },

  // ===== KENNEDY =====
  {
    id: "dr-aguirre-fernando",
    name: "Dr. Fernando Aguirre Macías",
    specialty: "Traumatología",
    hospitalId: "kennedy",
    hospitalName: "Hospital Kennedy",
    rating: 4.4,
    yearsExperience: 14,
    languages: ["es"],
    schedule: "Lun-Vie 8:00-14:00",
    bio: "Traumatólogo, cirugía artroscópica.",
  },
  {
    id: "dra-rivadeneira-paola",
    name: "Dra. Paola Rivadeneira Solís",
    specialty: "Ginecología",
    hospitalId: "kennedy",
    hospitalName: "Hospital Kennedy",
    rating: 4.5,
    yearsExperience: 18,
    languages: ["es", "en"],
    schedule: "Lun-Vie 9:00-15:00",
    bio: "Ginecóloga obstetra.",
  },

  // ===== OMNI =====
  {
    id: "dra-bravo-gabriela",
    name: "Dra. Gabriela Bravo Coello",
    specialty: "Reumatología",
    hospitalId: "omni",
    hospitalName: "Hospital Omni Hospital",
    rating: 4.6,
    yearsExperience: 15,
    languages: ["es", "en"],
    schedule: "Mar-Sáb 9:00-13:00",
    bio: "Reumatóloga, especialista en artritis reumatoide y fibromialgia.",
  },
  {
    id: "dr-paredes-david",
    name: "Dr. David Paredes Mosquera",
    specialty: "Cardiología",
    hospitalId: "omni",
    hospitalName: "Hospital Omni Hospital",
    rating: 4.5,
    yearsExperience: 17,
    languages: ["es"],
    schedule: "Lun-Vie 14:00-19:00",
    bio: "Cardiólogo, ecocardiografía e hipertensión.",
  },
  {
    id: "dr-chavez-roberto",
    name: "Dr. Roberto Chávez Pico",
    specialty: "Emergencias",
    hospitalId: "omni",
    hospitalName: "Hospital Omni Hospital",
    rating: 4.3,
    yearsExperience: 10,
    languages: ["es"],
    schedule: "24 horas con turnos rotativos",
    bio: "Médico emergenciólogo.",
  },

  // ===== VERNAZA =====
  {
    id: "dra-cevallos-ana",
    name: "Dra. Ana Cevallos Holguín",
    specialty: "Medicina General",
    hospitalId: "vernaza",
    hospitalName: "Hospital Luis Vernaza",
    rating: 4.2,
    yearsExperience: 19,
    languages: ["es"],
    schedule: "Lun-Vie 7:00-13:00",
    bio: "Internista de la Junta de Beneficencia.",
  },
  {
    id: "dr-leon-galo",
    name: "Dr. Galo León Guerrero",
    specialty: "Neurología",
    hospitalId: "vernaza",
    hospitalName: "Hospital Luis Vernaza",
    rating: 4.0,
    yearsExperience: 28,
    languages: ["es"],
    schedule: "Mar-Jue 9:00-12:00",
    bio: "Neurólogo con experiencia en patología cerebrovascular.",
  },

  // ===== MONTE SINAÍ (Cuenca) =====
  {
    id: "dra-cardenas-ana",
    name: "Dra. Ana Cárdenas Riofrío",
    specialty: "Traumatología",
    hospitalId: "monte_sinai",
    hospitalName: "Hospital Monte Sinaí",
    rating: 4.6,
    yearsExperience: 13,
    languages: ["es", "en"],
    schedule: "Lun-Vie 8:00-14:00",
    bio: "Traumatóloga, cirugía de mano y rodilla.",
  },
  {
    id: "dr-tinoco-marco",
    name: "Dr. Marco Tinoco Pesántez",
    specialty: "Cardiología",
    hospitalId: "monte_sinai",
    hospitalName: "Hospital Monte Sinaí",
    rating: 4.5,
    yearsExperience: 18,
    languages: ["es"],
    schedule: "Lun-Vie 9:00-13:00",
    bio: "Cardiólogo clínico.",
  },

  // ===== DEL RÍO =====
  {
    id: "dra-loyola-nadia",
    name: "Dra. Nadia Loyola Vintimilla",
    specialty: "Reumatología",
    hospitalId: "del_rio",
    hospitalName: "Hospital del Río",
    rating: 4.7,
    yearsExperience: 16,
    languages: ["es", "en"],
    schedule: "Mar-Vie 9:00-13:00",
    bio: "Reumatóloga, atención de pacientes con artritis y lupus.",
  },
  {
    id: "dr-cordero-pedro",
    name: "Dr. Pedro Cordero Crespo",
    specialty: "Traumatología",
    hospitalId: "del_rio",
    hospitalName: "Hospital del Río",
    rating: 4.5,
    yearsExperience: 11,
    languages: ["es"],
    schedule: "Lun-Vie 7:30-13:30",
    bio: "Traumatólogo, esguinces y fracturas.",
  },
  {
    id: "dra-pesantez-monica",
    name: "Dra. Mónica Pesántez Astudillo",
    specialty: "Pediatría",
    hospitalId: "del_rio",
    hospitalName: "Hospital del Río",
    rating: 4.8,
    yearsExperience: 20,
    languages: ["es", "en"],
    schedule: "Lun-Vie 8:00-13:00 y 15:00-18:00",
    bio: "Pediatra de cabecera, control de niño sano y atención general.",
  },

  // ===== IESS MANTA =====
  {
    id: "dr-zambrano-eduardo",
    name: "Dr. Eduardo Zambrano Mendoza",
    specialty: "Medicina General",
    hospitalId: "iess_manta",
    hospitalName: "Hospital IESS Manta",
    rating: 3.9,
    yearsExperience: 15,
    languages: ["es"],
    schedule: "Lun-Vie 7:00-15:00",
    bio: "Médico general del IESS.",
  },
  {
    id: "dra-cedeno-rosa",
    name: "Dra. Rosa Cedeño Vélez",
    specialty: "Reumatología",
    hospitalId: "iess_manta",
    hospitalName: "Hospital IESS Manta",
    rating: 4.0,
    yearsExperience: 17,
    languages: ["es"],
    schedule: "Mar-Jue 8:00-13:00",
    bio: "Reumatóloga del IESS, atención del adulto mayor.",
  },
];
