import type { EventoAtencion, IdPaciente } from "@/lib/tipos";

/**
 * Historial de atención simulado para cada paciente.
 * Útil para que el agente conozca el contexto previo del usuario.
 */
export const SEED_HISTORIALES: Record<IdPaciente, EventoAtencion[]> = {
  juan: [
    {
      fecha: "2025-09-12",
      hospitalId: "alcivar",
      hospitalName: "Hospital Alcívar",
      doctorName: "Dra. María Sánchez",
      especialidad: "Cardiología",
      motivo: "Control de hipertensión",
      diagnostico: "Hipertensión arterial estable, ajuste de losartán",
      copago: 16,
      total: 80,
    },
    {
      fecha: "2026-02-04",
      hospitalId: "alcivar",
      hospitalName: "Hospital Alcívar",
      doctorName: "Dr. Pablo Vera",
      especialidad: "Medicina General",
      motivo: "Cuadro gripal",
      diagnostico: "Infección respiratoria viral",
      copago: 12,
      total: 60,
    },
    {
      fecha: "2026-04-22",
      hospitalId: "alcivar",
      hospitalName: "Hospital Alcívar",
      doctorName: "Dra. María Sánchez",
      especialidad: "Cardiología",
      motivo: "Control de hipertensión",
      diagnostico: "HTA controlada, mantener tratamiento",
      copago: 16,
      total: 80,
    },
  ],

  maria: [
    {
      fecha: "2025-08-15",
      hospitalId: "metropolitano",
      hospitalName: "Hospital Metropolitano",
      doctorName: "Dra. Paula Mendoza",
      especialidad: "Neurología",
      motivo: "Migraña refractaria",
      diagnostico: "Migraña crónica con aura, inicio de profilaxis con topiramato",
      copago: 33,
      total: 110,
    },
    {
      fecha: "2025-12-03",
      hospitalId: "axxis",
      hospitalName: "Hospital Axxis",
      doctorName: "Dra. Sofía Ortega",
      especialidad: "Neurología",
      motivo: "Crisis migrañosa intensa",
      diagnostico: "Migraña refractaria, requirió manejo IV en sala",
      copago: 32,
      total: 105,
    },
    {
      fecha: "2026-03-18",
      hospitalId: "metropolitano",
      hospitalName: "Hospital Metropolitano",
      doctorName: "Dra. Paula Mendoza",
      especialidad: "Neurología",
      motivo: "Control de migraña",
      diagnostico: "Mejora parcial con topiramato, ajuste de dosis",
      copago: 33,
      total: 110,
    },
  ],

  pedro: [
    {
      fecha: "2025-11-08",
      hospitalId: "alcivar",
      hospitalName: "Hospital Alcívar",
      doctorName: "Dra. María Sánchez",
      especialidad: "Cardiología",
      motivo: "Chequeo cardiovascular trimestral",
      diagnostico: "Diabetes tipo 2 controlada, función cardíaca normal",
      copago: 0,
      total: 80,
    },
    {
      fecha: "2026-02-15",
      hospitalId: "alcivar",
      hospitalName: "Hospital Alcívar",
      doctorName: "Dra. María Sánchez",
      especialidad: "Cardiología",
      motivo: "Chequeo cardiovascular trimestral",
      diagnostico: "Diabetes tipo 2 estable, ECG y eco normales",
      copago: 0,
      total: 80,
    },
  ],

  lucia: [
    {
      fecha: "2025-11-29",
      hospitalId: "monte_sinai",
      hospitalName: "Hospital Monte Sinaí",
      doctorName: "Dr. Marco Tinoco",
      especialidad: "Medicina General",
      motivo: "Cuadro gripal severo",
      diagnostico: "IRA viral con sobreinfección bacteriana",
      copago: 19,
      total: 75,
    },
  ],

  roberto: [
    {
      fecha: "2025-08-20",
      hospitalId: "iess_manta",
      hospitalName: "Hospital IESS Manta",
      doctorName: "Dra. Rosa Cedeño",
      especialidad: "Reumatología",
      motivo: "Control de artritis",
      diagnostico: "Artritis reumatoide en remisión, mantener metotrexato",
      copago: 0,
      total: 0,
    },
    {
      fecha: "2025-11-18",
      hospitalId: "iess_manta",
      hospitalName: "Hospital IESS Manta",
      doctorName: "Dra. Rosa Cedeño",
      especialidad: "Reumatología",
      motivo: "Brote articular",
      diagnostico: "Reactivación de artritis, infiltración con corticoide",
      copago: 0,
      total: 0,
    },
    {
      fecha: "2026-02-09",
      hospitalId: "omni",
      hospitalName: "Hospital Omni Hospital",
      doctorName: "Dra. Gabriela Bravo",
      especialidad: "Reumatología",
      motivo: "Segunda opinión",
      diagnostico: "Confirmación AR, ajuste con biológico anti-TNF",
      copago: 18,
      total: 90,
    },
    {
      fecha: "2026-04-12",
      hospitalId: "iess_manta",
      hospitalName: "Hospital IESS Manta",
      doctorName: "Dra. Rosa Cedeño",
      especialidad: "Cardiología",
      motivo: "Control de hipertensión",
      diagnostico: "HTA estable",
      copago: 0,
      total: 0,
    },
  ],
};
