import type { Hospital } from "@/lib/tipos";

/**
 * 12 hospitales reales del Ecuador con coordenadas aproximadas, especialidades
 * y aseguradoras aceptadas. Solo usado al sembrar — el runtime lee de AI Search.
 */
export const SEED_HOSPITALES: Hospital[] = [
  // ===== QUITO =====
  {
    id: "metropolitano",
    name: "Hospital Metropolitano",
    type: "privado",
    level: 4,
    city: "Quito",
    district: "La Granja",
    address: "Av. Mariana de Jesús Oe7-2 y Av. Occidental",
    lat: -0.1856,
    lng: -78.4830,
    phone: "(02) 226-1520",
    fee: 110,
    rating: 4.7,
    wait: 18,
    specialties: [
      "Cardiología", "Neurología", "Traumatología", "Gastroenterología",
      "Oftalmología", "Pediatría", "Ginecología", "Urología", "Reumatología",
      "Oncología", "Medicina General", "Emergencias",
    ],
    acceptsInsurers: ["Aegis Salud", "Vital+", "Solaris Med"],
    services: ["emergencia24h", "hospitalizacion", "cirugia", "laboratorio", "imagen"],
    description:
      "Hospital privado de cuarto nivel en el norte de Quito, considerado uno de los más completos del país.",
  },
  {
    id: "voz_andes",
    name: "Hospital Voz Andes",
    type: "privado",
    level: 3,
    city: "Quito",
    district: "La Mariscal",
    address: "Villalengua Oe2-37 y Av. 10 de Agosto",
    lat: -0.1956,
    lng: -78.4900,
    phone: "(02) 397-1000",
    fee: 95,
    rating: 4.5,
    wait: 22,
    specialties: [
      "Cardiología", "Neurología", "Traumatología", "Pediatría",
      "Ginecología", "Medicina General", "Emergencias", "Reumatología",
    ],
    acceptsInsurers: ["Aegis Salud", "Vital+"],
    services: ["emergencia24h", "hospitalizacion", "cirugia", "laboratorio", "imagen"],
    description:
      "Hospital evangélico privado, más de 65 años de servicio en Quito centro-norte.",
  },
  {
    id: "axxis",
    name: "Hospital Axxis",
    type: "privado",
    level: 3,
    city: "Quito",
    district: "La Floresta",
    address: "Av. 10 de Agosto N39-155 y Diguja",
    lat: -0.1814,
    lng: -78.4830,
    phone: "(02) 245-8000",
    fee: 105,
    rating: 4.6,
    wait: 16,
    specialties: [
      "Cardiología", "Neurología", "Traumatología", "Gastroenterología",
      "Pediatría", "Ginecología", "Reumatología", "Endocrinología",
      "Medicina General", "Emergencias",
    ],
    acceptsInsurers: ["Aegis Salud", "Vital+", "Solaris Med"],
    services: ["emergencia24h", "hospitalizacion", "cirugia", "laboratorio", "imagen"],
    description:
      "Hospital privado moderno, especializado en alta complejidad y rehabilitación.",
  },
  {
    id: "de_los_valles",
    name: "Hospital de los Valles",
    type: "privado",
    level: 3,
    city: "Quito",
    district: "Cumbayá",
    address: "Av. Interoceánica km 12.5 y Av. de Los Conquistadores",
    lat: -0.1990,
    lng: -78.4290,
    phone: "(02) 297-7000",
    fee: 100,
    rating: 4.6,
    wait: 14,
    specialties: [
      "Cardiología", "Traumatología", "Pediatría", "Ginecología",
      "Medicina General", "Emergencias", "Endocrinología",
    ],
    acceptsInsurers: ["Aegis Salud", "Vital+"],
    services: ["emergencia24h", "hospitalizacion", "cirugia", "laboratorio", "imagen", "maternidad"],
    description:
      "Hospital privado en el valle de Cumbayá, atiende al sector oriental de Quito.",
  },
  {
    id: "carlos_andrade",
    name: "Hospital Carlos Andrade Marín",
    type: "iess",
    level: 4,
    city: "Quito",
    district: "Centro Norte",
    address: "Av. 18 de Septiembre y Ayacucho",
    lat: -0.1799,
    lng: -78.4831,
    phone: "(02) 256-2400",
    fee: 0,
    rating: 4.0,
    wait: 95,
    specialties: [
      "Cardiología", "Neurología", "Traumatología", "Gastroenterología",
      "Oftalmología", "Pediatría", "Ginecología", "Urología",
      "Reumatología", "Oncología", "Medicina General", "Emergencias",
    ],
    acceptsInsurers: ["IESS"],
    services: ["emergencia24h", "hospitalizacion", "cirugia", "laboratorio", "imagen"],
    description:
      "Hospital de especialidades del IESS — atención gratuita para afiliados.",
  },

  // ===== GUAYAQUIL =====
  {
    id: "alcivar",
    name: "Hospital Alcívar",
    type: "privado",
    level: 4,
    city: "Guayaquil",
    district: "Coronel",
    address: "Coronel 2301 y Azuay",
    lat: -2.1900,
    lng: -79.8930,
    phone: "(04) 372-0100",
    fee: 80,
    rating: 4.5,
    wait: 15,
    specialties: [
      "Cardiología", "Neurología", "Traumatología", "Gastroenterología",
      "Oftalmología", "Pediatría", "Ginecología", "Urología",
      "Medicina General", "Emergencias", "Reumatología",
    ],
    acceptsInsurers: ["Aegis Salud", "Vital+", "Solaris Med"],
    services: ["emergencia24h", "hospitalizacion", "cirugia", "laboratorio", "imagen"],
    description:
      "Hospital privado con más de 80 años de trayectoria en Guayaquil.",
  },
  {
    id: "kennedy",
    name: "Hospital Kennedy",
    type: "privado",
    level: 3,
    city: "Guayaquil",
    district: "Norte",
    address: "Av. del Periodista y San Jorge",
    lat: -2.1430,
    lng: -79.9020,
    phone: "(04) 228-9666",
    fee: 95,
    rating: 4.4,
    wait: 22,
    specialties: [
      "Cardiología", "Neurología", "Traumatología", "Pediatría",
      "Ginecología", "Medicina General", "Emergencias", "Endocrinología",
    ],
    acceptsInsurers: ["Aegis Salud", "Vital+", "Solaris Med"],
    services: ["emergencia24h", "hospitalizacion", "cirugia", "laboratorio", "imagen"],
    description: "Hospital privado en el norte de Guayaquil.",
  },
  {
    id: "omni",
    name: "Hospital Omni Hospital",
    type: "privado",
    level: 3,
    city: "Guayaquil",
    district: "Urdesa",
    address: "Av. Plaza Dañín y Av. Carlos Plaza Dañín",
    lat: -2.1690,
    lng: -79.9050,
    phone: "(04) 393-1000",
    fee: 90,
    rating: 4.3,
    wait: 20,
    specialties: [
      "Cardiología", "Traumatología", "Pediatría", "Ginecología",
      "Medicina General", "Emergencias", "Reumatología", "Urología",
    ],
    acceptsInsurers: ["Vital+", "Solaris Med"],
    services: ["emergencia24h", "hospitalizacion", "cirugia", "laboratorio", "imagen"],
    description: "Hospital privado moderno en Urdesa, Guayaquil.",
  },
  {
    id: "vernaza",
    name: "Hospital Luis Vernaza",
    type: "privado",
    level: 3,
    city: "Guayaquil",
    district: "Centro",
    address: "Loja 700 y Escobedo",
    lat: -2.1990,
    lng: -79.8770,
    phone: "(04) 256-0300",
    fee: 75,
    rating: 4.2,
    wait: 35,
    specialties: [
      "Cardiología", "Neurología", "Traumatología", "Gastroenterología",
      "Pediatría", "Medicina General", "Emergencias",
    ],
    acceptsInsurers: ["Junta de Beneficencia", "Aegis Salud"],
    services: ["emergencia24h", "hospitalizacion", "cirugia", "laboratorio"],
    description:
      "Hospital benéfico fundado en 1564, el más antiguo de Sudamérica en operación continua.",
  },

  // ===== CUENCA =====
  {
    id: "monte_sinai",
    name: "Hospital Monte Sinaí",
    type: "privado",
    level: 3,
    city: "Cuenca",
    district: "Sector Aeropuerto",
    address: "Miguel Cordero 6-111 y Av. Solano",
    lat: -2.9020,
    lng: -79.0190,
    phone: "(07) 288-5595",
    fee: 75,
    rating: 4.5,
    wait: 18,
    specialties: [
      "Cardiología", "Traumatología", "Pediatría", "Ginecología",
      "Medicina General", "Emergencias", "Reumatología",
    ],
    acceptsInsurers: ["Aegis Salud", "Vital+"],
    services: ["emergencia24h", "hospitalizacion", "cirugia", "laboratorio", "imagen"],
    description: "Hospital privado de referencia en el austro ecuatoriano.",
  },
  {
    id: "del_rio",
    name: "Hospital del Río",
    type: "privado",
    level: 3,
    city: "Cuenca",
    district: "Norte",
    address: "Av. de las Américas y Av. 24 de Mayo",
    lat: -2.9080,
    lng: -79.0230,
    phone: "(07) 408-0888",
    fee: 80,
    rating: 4.6,
    wait: 16,
    specialties: [
      "Cardiología", "Neurología", "Traumatología", "Gastroenterología",
      "Pediatría", "Ginecología", "Medicina General", "Emergencias",
      "Reumatología", "Endocrinología",
    ],
    acceptsInsurers: ["Aegis Salud", "Vital+", "Solaris Med"],
    services: ["emergencia24h", "hospitalizacion", "cirugia", "laboratorio", "imagen"],
    description: "Hospital privado moderno con tecnología de cuarto nivel.",
  },

  // ===== MANTA =====
  {
    id: "iess_manta",
    name: "Hospital IESS Manta",
    type: "iess",
    level: 2,
    city: "Manta",
    district: "Tarqui",
    address: "Av. 24 y calle 39",
    lat: -0.9540,
    lng: -80.7330,
    phone: "(05) 262-0500",
    fee: 0,
    rating: 3.9,
    wait: 80,
    specialties: [
      "Cardiología", "Pediatría", "Ginecología", "Medicina General",
      "Emergencias", "Traumatología",
    ],
    acceptsInsurers: ["IESS", "Vital+"],
    services: ["emergencia24h", "hospitalizacion", "cirugia", "laboratorio"],
    description: "Hospital del IESS en Manta — referente para la provincia de Manabí.",
  },
];
