import type { Paciente } from "@/lib/tipos";

/**
 * Datos sintéticos de pacientes — la única fuente en código.
 * Esta semilla se sube a Azure Blob (`pacientes/{id}.json`) la primera vez
 * que se llama a /api/admin/seed. A partir de ahí el runtime lee los
 * pacientes de Blob, no de este archivo.
 *
 * Aseguradoras y nombres son ficticios (HackIAthon Viamatica 2026).
 */
export const SEED_PACIENTES: Paciente[] = [
  {
    id: "juan",
    name: "Juan Pérez Bermúdez",
    initials: "JP",
    age: 54,
    case: "routine",
    caseTone: "green",
    caseLabel: { es: "Rutinario", en: "Routine" },
    city: "Guayaquil",
    insurer: "Aegis Salud",
    insurerMark: "A",
    insurerTone: "green",
    plan: "Essential 50",
    policyNo: "AS-2024-0187432",
    validity: "15 mar 2024 a 15 mar 2027",
    deductible: { annual: 1000, used: 850 },
    coverages: [
      { type: { es: "Emergencia", en: "Emergency" }, pct: 100 },
      { type: { es: "Hospitalización", en: "Hospitalization" }, pct: 90 },
      { type: { es: "Consulta externa", en: "Outpatient" }, pct: 80 },
      { type: { es: "Cirugía", en: "Surgery" }, pct: 80 },
    ],
    network: ["alcivar", "kennedy", "metropolitano"],
    preexisting: ["Hipertensión arterial"],
    seedQuery: {
      es: "Hola, llevo 2 días con dolor de cabeza fuerte y veo borroso a ratos.",
      en: "Hi, I've had a strong headache for 2 days and blurred vision at times.",
    },
    specialty: { es: "Neurología", en: "Neurology" },
  },
  {
    id: "maria",
    name: "María Fernanda López Vera",
    initials: "ML",
    age: 42,
    case: "preexisting",
    caseTone: "amber",
    caseLabel: { es: "Pre-existencia", en: "Pre-existing" },
    city: "Quito",
    insurer: "Vital+",
    insurerMark: "V",
    insurerTone: "amber",
    plan: "World Access",
    policyNo: "VP-2023-9981102",
    validity: "01 jul 2023 a 01 jul 2026",
    deductible: { annual: 800, used: 320 },
    coverages: [
      { type: { es: "Emergencia", en: "Emergency" }, pct: 100 },
      { type: { es: "Hospitalización", en: "Hospitalization" }, pct: 85 },
      { type: { es: "Consulta externa", en: "Outpatient" }, pct: 70 },
      { type: { es: "Maternidad", en: "Maternity" }, pct: 0 },
    ],
    network: ["metropolitano", "axxis", "kennedy"],
    preexisting: ["Migraña crónica"],
    seedQuery: {
      es: "Hola, tengo una migraña que no se va con paracetamol desde anoche.",
      en: "Hi, I've got a migraine that paracetamol won't fix since last night.",
    },
    specialty: { es: "Neurología", en: "Neurology" },
  },
  {
    id: "pedro",
    name: "Pedro Antonio Morales Cedeño",
    initials: "PM",
    age: 60,
    case: "redflag",
    caseTone: "red",
    caseLabel: { es: "Señal de alarma", en: "Red flag" },
    city: "Guayaquil",
    insurer: "Solaris Med",
    insurerMark: "S",
    insurerTone: "red",
    plan: "Enfermedades Graves",
    policyNo: "SM-2022-4480091",
    validity: "10 ene 2022 a 10 ene 2027",
    deductible: { annual: 1500, used: 0 },
    coverages: [
      { type: { es: "Emergencia", en: "Emergency" }, pct: 100 },
      { type: { es: "Hospitalización", en: "Hospitalization" }, pct: 100 },
      { type: { es: "Consulta externa", en: "Outpatient" }, pct: 60 },
      { type: { es: "Cirugía cardíaca", en: "Cardiac surgery" }, pct: 100 },
    ],
    network: ["alcivar", "kennedy", "omni"],
    preexisting: ["Diabetes tipo 2"],
    seedQuery: {
      es: "Tengo dolor en el pecho que se va al brazo izquierdo y sudo frío.",
      en: "I have chest pain spreading to my left arm and I'm sweating cold.",
    },
    specialty: { es: "Cardiología / Emergencias", en: "Cardiology / Emergency" },
  },
  {
    id: "lucia",
    name: "Lucía Estefanía Cárdenas Riofrío",
    initials: "LC",
    age: 28,
    case: "deductible",
    caseTone: "amber",
    caseLabel: { es: "Deducible nuevo", en: "Fresh deductible" },
    city: "Cuenca",
    insurer: "Aegis Salud",
    insurerMark: "A",
    insurerTone: "green",
    plan: "Joven Plus",
    policyNo: "AS-2025-3344210",
    validity: "01 ene 2025 a 01 ene 2027",
    deductible: { annual: 500, used: 0 },
    coverages: [
      { type: { es: "Emergencia", en: "Emergency" }, pct: 100 },
      { type: { es: "Hospitalización", en: "Hospitalization" }, pct: 80 },
      { type: { es: "Consulta externa", en: "Outpatient" }, pct: 75 },
      { type: { es: "Traumatología", en: "Trauma" }, pct: 80 },
    ],
    network: ["metropolitano", "axxis", "alcivar"],
    preexisting: [],
    seedQuery: {
      es: "Me torcí el tobillo bajando las gradas y se está hinchando rápido.",
      en: "I twisted my ankle on the stairs and it is swelling fast.",
    },
    specialty: { es: "Traumatología", en: "Trauma" },
  },
  {
    id: "roberto",
    name: "Roberto Andrés Salas Mora",
    initials: "RS",
    age: 67,
    case: "preexisting",
    caseTone: "amber",
    caseLabel: { es: "Adulto mayor", en: "Senior" },
    city: "Manta",
    insurer: "Vital+",
    insurerMark: "V",
    insurerTone: "amber",
    plan: "Senior Care 65+",
    policyNo: "VP-2021-7720418",
    validity: "10 abr 2021 a 10 abr 2026",
    deductible: { annual: 1200, used: 1100 },
    coverages: [
      { type: { es: "Emergencia", en: "Emergency" }, pct: 100 },
      { type: { es: "Hospitalización", en: "Hospitalization" }, pct: 90 },
      { type: { es: "Consulta externa", en: "Outpatient" }, pct: 80 },
      { type: { es: "Reumatología", en: "Rheumatology" }, pct: 85 },
    ],
    network: ["axxis", "omni", "kennedy"],
    preexisting: ["Artritis reumatoide", "Hipertensión arterial"],
    seedQuery: {
      es: "Me duelen mucho las rodillas y las manos, sobre todo en las mañanas.",
      en: "My knees and hands hurt a lot, especially in the morning.",
    },
    specialty: { es: "Reumatología", en: "Rheumatology" },
  },
];
