import type { Procedimiento } from "@/lib/tipos";

/**
 * Catálogo de procedimientos médicos comunes con costos referenciales
 * en Ecuador (USD). No son tarifas oficiales — son rangos sintéticos
 * basados en mercado privado promedio.
 */
export const SEED_PROCEDIMIENTOS: Procedimiento[] = [
  {
    id: "consulta-general",
    name: "Consulta médica general",
    specialty: "Medicina General",
    avgCostLow: 25,
    avgCostHigh: 60,
    description: "Evaluación clínica básica, diagnóstico inicial y prescripción.",
  },
  {
    id: "consulta-especialista",
    name: "Consulta de especialista",
    specialty: "Especialidades",
    avgCostLow: 40,
    avgCostHigh: 120,
    description: "Atención por médico con sub-especialidad (cardiólogo, neurólogo, etc.).",
  },
  {
    id: "consulta-emergencia",
    name: "Atención en emergencia",
    specialty: "Emergencias",
    avgCostLow: 35,
    avgCostHigh: 90,
    description: "Triage y evaluación inicial en sala de emergencias.",
  },
  {
    id: "rx-extremidad",
    name: "Radiografía de extremidad",
    specialty: "Imagen",
    avgCostLow: 20,
    avgCostHigh: 50,
    description: "Imagen de mano, pie, rodilla o codo para descartar fracturas.",
  },
  {
    id: "rx-torax",
    name: "Radiografía de tórax",
    specialty: "Imagen",
    avgCostLow: 25,
    avgCostHigh: 60,
    description: "Imagen torácica para evaluar pulmones y silueta cardíaca.",
  },
  {
    id: "ecografia-abdominal",
    name: "Ecografía abdominal",
    specialty: "Imagen",
    avgCostLow: 35,
    avgCostHigh: 80,
    description: "Estudio ultrasónico de hígado, riñones, vesícula y bazo.",
    requires: "Ayuno mínimo 6 horas",
  },
  {
    id: "ecografia-obstetrica",
    name: "Ecografía obstétrica",
    specialty: "Ginecología",
    avgCostLow: 40,
    avgCostHigh: 90,
    description: "Control de embarazo y bienestar fetal.",
  },
  {
    id: "tomografia",
    name: "Tomografía simple",
    specialty: "Imagen",
    avgCostLow: 80,
    avgCostHigh: 200,
    description: "Tomografía computada de cráneo, abdomen o tórax.",
  },
  {
    id: "resonancia-magnetica",
    name: "Resonancia magnética",
    specialty: "Imagen",
    avgCostLow: 180,
    avgCostHigh: 450,
    description: "Estudio de alta resolución para neurología, articulaciones y partes blandas.",
  },
  {
    id: "biometria-hematica",
    name: "Biometría hemática completa",
    specialty: "Laboratorio",
    avgCostLow: 8,
    avgCostHigh: 25,
    description: "Análisis de glóbulos rojos, blancos y plaquetas.",
  },
  {
    id: "perfil-lipidico",
    name: "Perfil lipídico",
    specialty: "Laboratorio",
    avgCostLow: 18,
    avgCostHigh: 45,
    description: "Colesterol total, HDL, LDL y triglicéridos.",
    requires: "Ayuno 12 horas",
  },
  {
    id: "glucosa-ayunas",
    name: "Glucosa en ayunas",
    specialty: "Laboratorio",
    avgCostLow: 5,
    avgCostHigh: 15,
    description: "Medición de azúcar en sangre.",
    requires: "Ayuno 8 horas",
  },
  {
    id: "electrocardiograma",
    name: "Electrocardiograma (EKG)",
    specialty: "Cardiología",
    avgCostLow: 20,
    avgCostHigh: 50,
    description: "Registro de actividad eléctrica del corazón.",
  },
  {
    id: "ecocardiograma",
    name: "Ecocardiograma",
    specialty: "Cardiología",
    avgCostLow: 80,
    avgCostHigh: 180,
    description: "Ultrasonido del corazón para evaluar función y estructura.",
  },
  {
    id: "holter-24h",
    name: "Holter de 24 horas",
    specialty: "Cardiología",
    avgCostLow: 90,
    avgCostHigh: 200,
    description: "Monitoreo cardiaco continuo durante un día.",
  },
  {
    id: "endoscopia-alta",
    name: "Endoscopia digestiva alta",
    specialty: "Gastroenterología",
    avgCostLow: 120,
    avgCostHigh: 280,
    description: "Examen del esófago, estómago y duodeno.",
    requires: "Ayuno 8 horas",
  },
  {
    id: "colonoscopia",
    name: "Colonoscopia",
    specialty: "Gastroenterología",
    avgCostLow: 220,
    avgCostHigh: 500,
    description: "Examen completo del colon con sedación.",
    requires: "Preparación intestinal de 24 horas",
  },
  {
    id: "sutura-simple",
    name: "Sutura simple de herida",
    specialty: "Cirugía menor",
    avgCostLow: 30,
    avgCostHigh: 90,
    description: "Cierre de heridas pequeñas con anestesia local.",
  },
  {
    id: "yeso-extremidad",
    name: "Inmovilización con yeso",
    specialty: "Traumatología",
    avgCostLow: 35,
    avgCostHigh: 90,
    description: "Yeso o férula para fracturas o esguinces severos.",
  },
  {
    id: "fisioterapia-sesion",
    name: "Sesión de fisioterapia",
    specialty: "Rehabilitación",
    avgCostLow: 20,
    avgCostHigh: 50,
    description: "Terapia física para recuperación de lesiones musculoesqueléticas.",
  },
];
